# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.genesis_pegaeon.root] run return 0
execute on passengers if entity @s[tag=aj.genesis_pegaeon.data] unless data entity @s {data:{rigHash: '043e1c964a8e5e8a6fe811d6bd7415dfeb0e0c40d26a9bb48af782b294fde3b1'}} on vehicle run function animated_java:genesis_pegaeon/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1