# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.genesis_pegaeon.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.genesis_pegaeon.animation.idle.playing] run function animated_java:genesis_pegaeon/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.genesis_pegaeon.animation.take_off.playing] run function animated_java:genesis_pegaeon/animations/take_off/zzz/on_tick
execute if entity @s[tag=aj.genesis_pegaeon.animation.flying.playing] run function animated_java:genesis_pegaeon/animations/flying/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~