# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.genesis_pegaeon.node.tail] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_tail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.genesis_pegaeon.node.head_feathers] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head_feathers set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.genesis_pegaeon.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.genesis_pegaeon.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.genesis_pegaeon.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.genesis_pegaeon.node.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.genesis_pegaeon.node.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.genesis_pegaeon.node.1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.genesis_pegaeon.node.right_wing] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_wing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.genesis_pegaeon.node.2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.genesis_pegaeon.node.left_wing] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_wing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.genesis_pegaeon.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out