# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_tail) {transformation: [-1.125f,0f,0f,0f,0f,1.0394f,0.4305f,0f,0f,0.4305f,-1.0394f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head_feathers) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5625f,0f,0f,-1f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-1f,0f,0f,-0.3125f,0f,1f,0f,-0.25f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-1f,0f,0f,0.3125f,0f,1f,0f,-0.25f,0f,0f,-1f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-1f,0f,0f,-0.3125f,0f,1f,0f,-0.25f,0f,0f,-1f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-1f,0f,0f,0.3125f,0f,1f,0f,-0.25f,0f,0f,-1f,0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_1) {transformation: [-0.1585f,-1.0368f,0.5108f,-0.9869f,0.1516f,0.4925f,1.0467f,-1.079f,-1.1459f,0.2086f,0.0678f,0.1939f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_wing) {transformation: [-0.4457f,-0.9072f,0.1428f,-0.375f,-0.6742f,0.431f,0.634f,0f,-0.6237f,0.1825f,-0.7873f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_2) {transformation: [-0.1585f,1.0368f,-0.5108f,0.9869f,-0.1516f,0.4925f,1.0467f,-1.079f,1.1459f,0.2086f,0.0678f,0.1939f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_wing) {transformation: [-0.4457f,0.9072f,-0.1428f,0.375f,0.6742f,0.431f,0.634f,0f,0.6237f,0.1825f,-0.7873f,0.6875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.25f,0f,0f,-1f,0.25f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}