# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.genesis_pegaeon.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'genesis_pegaeon', 'function_path': 'animated_java:genesis_pegaeon/animations/take_off/next_frame'}
execute if score @s aj.take_off.frame matches 56.. run scoreboard players set @s aj.take_off.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.take_off.frame
execute at @s run function animated_java:genesis_pegaeon/animations/take_off/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.take_off.frame 1