# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.genesis_pegaeon.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'genesis_pegaeon', 'function_path': 'animated_java:genesis_pegaeon/animations/take_off/set_frame'}
data remove storage aj:temp args
$execute store result storage aj:temp args.frame int 1 run scoreboard players set @s aj.take_off.frame $(frame)
execute at @s run function animated_java:genesis_pegaeon/animations/take_off/zzz/set_frame with storage aj:temp args