# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.genesis_pegaeon.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'genesis_pegaeon', 'function_path': 'animated_java:genesis_pegaeon/animations/pause_all'}
tag @s remove aj.genesis_pegaeon.animation.idle.playing
tag @s remove aj.genesis_pegaeon.animation.take_off.playing
tag @s remove aj.genesis_pegaeon.animation.flying.playing