# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:genesis_pegaeon/animations/flying/zzz/apply_frame {frame: 40}
scoreboard players add @s aj.flying.frame 1